
decoyProts = {}

decoyProts["bqian_caspbench"] =      [ "t196_",
                                       "t199_",
                                       "t205_",
                                       "t206_",
                                       "t223_",
                                       "t224_",
                                       "t232_",
                                       "t234_",
                                       "t249_"  ]
decoyProts["sraman_nmr"] =           [ "1fvk_",
                                       "1hb6A",
                                       "1hoe_",
                                       "1i27_",
                                       "1who_",
                                       "2int_",
                                       "3il8_",
                                       "4rnt_"  ]
decoyProts["kira_hom"] =             [ "1a4pA",
                                       "1acf_",
                                       "1agi_",
                                       "1ahn_",
                                       "1ar0A",
                                       "1aw2A",
                                       "1b07A",
                                       "1be9A",
                                       "1bmbA",
                                       "1btn_",
                                       "1cfyA",
                                       "1crb_",
                                       "1d2nA",
                                       "1dol_",
                                       "1erv_",
                                       "1ig5_",
                                       "1pvaA",
                                       "1qavA"  ]
decoyProts["phil_homolog"] =         [ "1af7_",
                                       "1b72_",
                                       "1csp_",
                                       "1dcj_",
                                       "1di2_",
                                       "1dtj_",
                                       "1mky_",
                                       "1mla_",
                                       "1n0u_",
                                       #"1o2f_",
                                       "1ogw_",
                                       "1r69_",
                                       "1shf_",
                                       "1tif_",
                                       "1tig_",
                                       "2reb_"  ]
decoyProts["kira_bench"] =           [ "1aa3_",
                                       "1acp_",
                                       "1ail_",
                                       "1b72_",
                                       "1bf4_",
                                       "1ig5_",
                                       "1pgx_",
                                       "1r69_",
                                       "1tif_",
                                       "1tig_",
                                       "1utg_",
                                       "1vii_",
                                       "256b_"  ]
