import time,random

pathsTemplate = """Rosetta Input/Output Paths (order essential)
path is first '/','./', or '../' to next whitespace, must end with '/'
INPUT PATHS:
pdb1	                        %(pdb1)s/
pdb2                            %(pdb2)s/
alternate data files            %(alternate)s/
fragments                       %(fragments)s/
structure dssp,ssa (dat,jones)  %(structure)s/
sequence fasta,dat,jones        %(sequence)s/
constraints                     %(constraints)s/
starting structure              %(starting)s/
data files                      %(datafiles)s/
OUTPUT PATHS:
movie                           %(movie)s/
pdb path                        %(pdbout)s/
score                           %(score)s/
status                          %(status)s/
user                            %(user)s/
FRAGMENTS: (use '*****' in place of pdb name and chain)
2                                      number of valid fragment files
3                                      frag file 1 size
%(frags3)s                               name
9                                      frag file 2 size
%(frags9)s                               name
-------------------------------------------------------------------------
Autogenerated by python
Date:   %(date)s
Author: sheffler
-------------------------------------------------------------------------
"""


def makePathsFile(newpaths={},location='.',filename=None):
    pathsDefaults = {}
    pathsDefaults['pdb1']        = location
    pathsDefaults['pdb2']        = location+'/'+'rosetta_data'
    pathsDefaults['alternate']   = location
    pathsDefaults['fragments']   = location+'/'+'rosetta_data'
    pathsDefaults['structure']   = location+'/'+'rosetta_data'
    pathsDefaults['sequence']    = location+'/'+'rosetta_data'
    pathsDefaults['constraints'] = '/'
    pathsDefaults['starting']    = location
    pathsDefaults['datafiles']   = '/users/sheffler/data/rosetta_database/'
    pathsDefaults['movie']       = location
    pathsDefaults['pdbout']      = location
    pathsDefaults['score']       = location
    pathsDefaults['status']      = location
    pathsDefaults['user']        = location
    pathsDefaults['frags3']      = 'aa*****03_05.200_v1_3'
    pathsDefaults['frags9']      = 'aa*****09_05.200_v1_3'
    paths = pathsDefaults
    for k in newpaths:
        paths[k] = newpaths[k]
    paths['date'] = time.ctime()
    if filename is None:
        filename = location+"/.autopaths."+`random.random()`[2:]
    pathfile = open(filename,'w')
    pathfile.write(pathsTemplate%paths)
    pathfile.close()
    return filename
