#!/usr/bin/python
import sys

tplt = """Error   = log/%(LISTBASE)s_%(LOG)s.err
Output  = log/%(LISTBASE)s_%(LOG)s.out
args    = """ + sys.argv[1] + """ -l %(LIST)s
Queue 1
"""

LOG = ""

for LIST in sys.argv[2:]:
	LISTBASE = LIST.split("/")[-1].replace(".list","")
	print tplt % vars()
