#!/usr/bin/env python
import sys,os
for fn in sys.argv[1:]:
   print "pruning multi-occ for",fn
   o = open(fn+"TMP","w")
   for l in open(fn).xreadlines():
      if not l.startswith("ATOM") and not l.startswith("HETATM"):
         o.write(l)
         continue
      if l[16] == ' ':
         o.write(l)
         continue
      if float(l[56:60]) > 0.5: 
         o.write( l[:16]+" "+l[17:] )

   o.close()
   os.rename(fn+"TMP",fn)
